language: python

python: "2.7"

sudo: false

env:
  global:
    - "SITEURL=https://freenetproject.org"
    - "SHOULD_COMPRESS=True"
    - "AWS_ACCESS_KEY_ID=AKIAJQUIQIL3XTBHT3DA"
    # our AWS_SECRET_ACCESS_KEY follows
    - secure: "Q7jH10Hjul2kLwSRW09Q9vIaJTSZeolvHdHewT2nMwtRTWeINOHsOS61CaXg5t2VM4Ri2GbO0SjaNWqoyQyQSbQBPmOBG8bISd8LEdBErat5ZEiAIlgOSm/rnr6F7dq+zKtdy4v+jIMnnfkRpT62Rvx5fRzDEOc3PcJQWGQSQ05e7fSuvhWgS9T1OAsDwAPLyrEPhEwlkeDpfJt2FcZFCA1G9/3F/ej8OAvgfOEiZn1b9iy2FjSB7S969l0Nejs3c63cFWmC+CpzEqD6yXtkqN5A4VS3+P1xh+jBpoeCb/6MKM6QtxD7lE3ZvBevp5l01/H60Mgjd/g8JEKBMo+tk27bCd7X+9j7iPjdOrkPJTccu2s6UFE/VMJIYY44Kr2ugyKu6SGkAuNe6SzPP+LHFj5/OJLjKswsIxq1Vtxwvxx2PMNLQ4v6ZAwNG+x623EHQdbkmcI5lqxLgcQrWROOHxuA0aXY/CTW8V23VoDXQ8UJRimtOHXfHqC6Zwq84iRuyQf8SmycpShxA26QvjCFtMq/niDKuLWR20zzsTPII864bc99ZARqAhIQo56ZGRvvgnv2wLFqVHh9zc66MU9/nfMKPi2xEj9qYjFDkfwZH/sfpJFSC4gz7u3svrIE5rD5Z0dwILPtDAR5q46+hgFcjt8Q1jvteT6SS4nchSEZ/Bw="

cache:
  pip: true
  apt: true
  directories:
    - output

addons:
  apt:
    packages:
    - gettext
    - libjpeg-turbo-progs
    - optipng
    - python-pip
    - python-virtualenv

script: make html

deploy:
  - provider: script
    script: bash upload_to_s3.sh s3://website-staging.freenetproject.org/ 300
    skip_cleanup: true
    on:
      branch: 2016-redesign
